# Build a Docker image and push it to Docker Hub
name: Dockerize simeon

on:
  create:

jobs:
  docker:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        env:
          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mitir/simeon:${{ env.SOURCE_TAG }}
      -
        name: Publish Latest Tag
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mitir/simeon:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
